server :
 port : 0

spring :
 datasource:
    url: jdbc:mysql://localhost:3306/Ecommerce
    username : root
    password : ENC(mucK51N0lws9URsogCfoofotliXLnDnSzvJ4AL8bFX9d1Vp2eED3Vv6XrJ9GaG+J)
 jpa :
    database-platform : org.hibernate.dialect.MySQLDialect
    show-sql : true
    generate-ddl : true
    properties : 
      hibernate : 
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto : none

eureka:
   client:
    register-with-eureka: true
    fetch-registry: true
